name: fliq
description: Fliq is a simple and fluent Flutter library for building Restful clients with a focus on ease of use and readability. Supports cookies, interceptors and authentication.
version: 0.0.2
homepage: https://github.com/netesy/fliq
repository: https://github.com/netesy/fliq
documentation: https://github.com/netesy/fliq/example
issue_tracker: https://github.com/netesy/fliq/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - network
  - http
  - rest
  - api


environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true